### ISSUE TITLE
Authentication not working

### ISSUE THREAD

**Issue by Cheesiq** [orangopus/ollo#3]
Currently the authentication flow for libby isn't working. We get this error:

[next-auth][error][session_error] TypeError: Cannot read property 'name' of null
    at E:\libby\libby-web\node_modules\next-auth\dist\server\routes\session.js:99:26
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (E:\libby\libby-web\node_modules\next-auth\dist\server\routes\session.js:22:103)
    at _next (E:\libby\libby-web\node_modules\next-auth\dist\server\routes\session.js:24:194)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
https://next-auth.js.org/errors#session_error

This will be investigated until we find a fix.

**Comment by ovo** [comment]
I am getting this issue as well using next-auth and Prisma.

**Comment by Cheesiq** [comment]
> I am getting this issue as well using next-auth and Prisma.

Yeah same here. Reference to this issue here: https://github.com/nextauthjs/next-auth/issues/1106#issuecomment-759970451

Hope NextAuth knows what's wrong. Otherwise I'm going to have to use a completely new database and new auth flow.

**Comment by ovo** [comment]
> Hope NextAuth knows what's wrong. Otherwise I'm going to have to use a completely new database and new auth flow.

Same. I'm debating on just writing my own authentication middleware but it's just so tedious to do.

**Comment by Cheesiq** [comment]
We're probably going to migrate to a new authetincation and database infrastructure.

Closing this for now.
